version: '3.8'
services:
  backend:
    build: ./back
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app
  frontend:
    build: ./front
    working_dir: /usr/src/app
    command: npm run preview
    ports:
      - "5173:5173"
    volumes:
      - ./front:/usr/src/app
