# Remove version line (obsolete in newer Docker Compose)
services:
  backend:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  # Prevent overriding node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules  # Prevent overriding node_modules
    command: sh -c "npm install && npm run preview"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend